### ISSUE TITLE
@Delegate usage on http://groovyconsole.appspot.com/ makes it give a very weird error

### ISSUE THREAD

**Issue by roshandawrani** [glaforge/groovywebconsole#17]
Code to reproduce the error

class Temp {
    @Delegate GroovyShell shell = new GroovyShell()

```
static main(args) {
    println 'x'
}
```

}

Error reported is :

error: neither -e or filename provided
usage: groovy [options] [args]
options:
  -a,--autosplit <splitPattern>    split lines using splitPattern (default 's')
                                   using implicit 'split' variable
  -c,--encoding <charset>          specify the encoding of the files
  -D,--define <name=value>         define a system property
  -d,--debug                       debug mode will print out full stack traces
  -e <script>                      specify a command line script
  -h,--help                        usage information
  -i <extension>                   modify files in place; create backup if
                                   extension is given (e.g. '.bak')
  -l <port>                        listen on a port and process inbound lines
                                   (default: 1960)
  -n                               process files line by line using implicit
                                   'line' variable
  -p                               process files line by line and print result
                                   (see also -n)
  -v,--version                     display the Groovy and JVM versions

**Comment by hlaaftana** [comment]
[no it doesnt](https://groovyconsole.appspot.com/script/5074575062728704)

**Comment by glaforge** [comment]
Looks like it's working these days.
