### ISSUE TITLE
JSON serialization issue

### ISSUE THREAD

**Issue by bsideup** [glaforge/groovywebconsole#25]
This code will cause an Error on de-serialization:

``` groovy
​println '\\\"'​​
```

**Comment by mpictor** [comment]
I see a similar error for things like
```
def ​re =​ /(\d+\.\d+\.)\d+/​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
```

It's a shame this is still a problem after ~ 3.5 years :/

**Comment by glaforge** [comment]
Is there a pull request? :-P

**Comment by glaforge** [comment]
After many years, I eventually tweaked the JSON serialisation to fix those bugs :-)
