### ISSUE TITLE
Cannot publish script

### ISSUE THREAD

**Issue by luisepifanio** [glaforge/groovywebconsole#26]
Simply create a script with
println 'Groovy rocks'

Then "Publish script"
Script cannot be saved

**Comment by glaforge** [comment]
Thanks for reporting!
It seems people can still publish scripts (I see them through the RSS feed, so they are indeed saved), but it's likely the page displaying scripts which has a problem and says "no such script".

**Comment by glaforge** [comment]
I'm in vacations now, so not sure I'll be able to fix that quickly though, thanks for your patience.

**Comment by glaforge** [comment]
Should be fixed now!

**Comment by luisepifanio** [comment]
Great!
It's a great tool in my everyday scripting tests ( probably i'm just to lazy to save it and run groovy run.groovy ;) )
Thanks
