### ISSUE TITLE
Groovy Date extensions don't work as expected

### ISSUE THREAD

**Issue by mateusz-was** [glaforge/groovywebconsole#30]
For some reason the methods from DateUtilExtensions are missing.
The code breaks because `minus()` is not present.
It works in my local groovyConsole (Groovy 2.5.7).

I've tested recently following snippet:
```
import java.text.SimpleDateFormat

def now = new Date()
def from = now-20
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T23:59:59.999Z'")
println sdf.format(now)
println sdf.format(from)
```

**Comment by ppazos** [comment]
Detected the same with Date.clearTime: method not found

**Comment by rste79** [comment]
According to the download page:

http://groovy-lang.org/download.html

since groovy 2.5.0 the date time extensions are included in a separate jar (the datetime module).
So to resolve this issue it should be sufficient to add the jar to the war/WEB-INF/lib folder.
