### ISSUE TITLE
Update to Groovy 3

### ISSUE THREAD

**Issue by Vampire** [glaforge/groovywebconsole#32]
Would be nice to have an updated version for Groovy 3. :-)

**Comment by szpak** [comment]
I've bumped the same today trying to verify that some strange compiler behavior occurs also on some other machine.

**Comment by glaforge** [comment]
It's not easy to update to Groovy 3 or provide a Groovy 3 flavor, as some dependencies needed by the project won't work with Groovy 3.
That said, I'm working on a totally new Groovy Web Console, whose prototype can be seen here:
https://gwc-experiment.ew.r.appspot.com/
It'll allow you to pick up the version of Groovy you want. At least, the latest versions of the main branches, ie Groovy 2.5, Groovy 3, and Groovy 4 when it's out.
I'll be closing this ticket, as I won't upgrade / add Groovy 3 support in this old code base.

**Comment by Vampire** [comment]
That's great, thanks. :-)
Maybe a "little" suggestion that you could consider for that project.
It would be super-nice if you could either re-use https://github.com/AlexanderPrendota/kotlin-compiler-server as backend just adapted to compile and run Groovy instead of Kotlin, or at least would provide the same API that server is providing.

The background is this: https://issues.apache.org/jira/projects/GROOVY/issues/GROOVY-9975
If the new web console provides the same API the `kotlin-compiler-server` is providing, then it is a very minimal effort (basically changing an `if` to support Groovy and using a different URL for the back-end in the https://www.npmjs.com/package/kotlin-playground component.

This would instantly enable documentation, blogs and basically any website to have interactive syntax-highlighted editable runnable Groovy examples. For example look at the first two examples on https://kotlinlang.org/docs/null-safety.html#nullable-types-and-non-null-types, there you can see that component in action. I was even able to make it work for the happy path with the current codebase in this repository by allowing CORS and adapting the call and response processing in the playground component.

**Comment by glaforge** [comment]
When working on the new console experiment, the idea of having the ability to make the Groovy documentation have runnable code snippets was indeed in my mind. We'll see if we get to implement it, but that would be nice :-)

**Comment by Vampire** [comment]
That would really be awesome.
Especially as it should be relatively easy to reuse that component when you provide the same API on the compile server side. :-)

**Comment by Vampire** [comment]
Is the code of the new web console already shared somewhere or is it just private play up to now?

**Comment by leonard84** [comment]
> basically changing an if to support Groovy

we would still have to fork that library and release our own version, I don't know how receptive JetBrains would be to extract the common functionality into a base component.

**Comment by leonard84** [comment]
> Is the code of the new web console already shared somewhere or is it just private play up to now?

it is in a private repo at the moment

**Comment by glaforge** [comment]
> > Is the code of the new web console already shared somewhere or is it just private play up to now?
> 
> it is in a private repo at the moment

I've just made it public, in case others want to contribute too.
