### ISSUE TITLE
Run button on published code page

### ISSUE THREAD

**Issue by Deleplace** [glaforge/groovywebconsole#33]
It seems that the [Execute script] button exists in the Edit page, but not in the published Script page.

So when I share a canonical Script URL e.g. https://groovyconsole.appspot.com/script/5088073331245056 , the visitor must figure out they have to click [Edit in console] and then find the [Execute script] button.

How about adding this feature to the Script page?

Shall I try to implement it and make a PR?

**Comment by Deleplace** [comment]
PR #38

**Comment by glaforge** [comment]
Thanks for the PR, it's been deployed.
