### ISSUE TITLE
Symbol ➤ looks like "Play" (mistaken for Execute script)

### ISSUE THREAD

**Issue by Deleplace** [glaforge/groovywebconsole#37]
![image](https://user-images.githubusercontent.com/13508141/100237905-d648dd80-2f2f-11eb-9916-fde2ff799dbf.png)

I think it would be less confusing to remove the arrow. We may replace it with a colon.

**Comment by Deleplace** [comment]
Related to #33 because one would expect to find a "Play" button on the Script page.

**Comment by glaforge** [comment]
Good point, I hope this will be more natural and obvious that way:
<img width="533" alt="Screen Shot 2021-07-09 at 16 20 20" src="https://user-images.githubusercontent.com/47907/125092427-a242b700-e0d1-11eb-9e58-f3f373c610d4.png">
