### ISSUE TITLE
web site broken: "Error interacting with the Groovy web console server: error"

### ISSUE THREAD

**Issue by tony-kerz** [glaforge/groovywebconsole#39]
have used this site for years, super handy, never seen this before, but looks like the site is glitching with the above error from multiple browsers when "execute script" button is pushed no matter what code is in script window...

**Comment by glaforge** [comment]
Indeed, looks like it's now broken. But I haven't much time to investigate right now.

You should try to use the newer Groovy Web Console: https://gwc-experiment.appspot.com/
It's more up-to-date, with different versions of Groovy available.

**Comment by tony-kerz** [comment]
gwc-experiment works great, the only thing it really needs is a cool groovy icon 😄 
thanks g!
